# ---------------------------------------------------------------------------- #
# AUTHORS: Bia Dias, Andy Whitehouse
# AFFILIATIONS: CICOES University of Washington
# E-MAIL OF CORRESPONDENCE AUTHOR: bia.dias@noaa.gov
# DATE: 08 July 2026
#
# Script to run HCRs function
#
# 
# ---------------------------------------------------------------------------- #
source("code/08_function_hcrs.R")
load("~/goaclim_rpath/data/bftarget/06_run_btarget_ftarget.RData")
#NOTE: I need to fix this, so I don't need to rely on .RData. 


# ---------------------------------------------------------------------------- #
# Read reference point outputs from 06_run_btarget_ftarget_v1.R ####
# ---------------------------------------------------------------------------- #
bftarget_dir <- "data/bftarget"

# Biomass reference points (B0, B40, B40_SSB, Btarget_SQ, Blim, …)
target_bio <- read.csv(
  file.path(bftarget_dir, "B_SSB_target_WGOA_nosablepersist.csv"),
  row.names = 1
)

# Climate-informed Ftarget (one column per scenario; "persist" for now)
Ftarg_matrix <- read.csv(
  file.path(bftarget_dir, "F_Tier3_WGOA_persist_v2_nosablessb.csv"),
  row.names = 1
)

# Extract F40_ABC generated by the individual species optimization
F40_ABC <- Ftarg_matrix[, "F40_ABC"]
names(F40_ABC) <- rownames(Ftarg_matrix)

# Optional: Extract F35_OFL in case you want to implement OFL caps later
F35_OFL <- Ftarg_matrix[, "F35_OFL"]
names(F35_OFL) <- rownames(Ftarg_matrix)

F50 <- Ftarg_matrix[, "F50"]
names(F50) <- rownames(Ftarg_matrix)
B50 <- target_bio[, "B50"]
names(B50) <- rownames(target_bio)

# Set global F40 and B40 vectors for the HCR function to use
F40 <- F40_ABC
B40 <- target_bio[, "B40"]
names(B40) <- rownames(target_bio)



# ---------------------------------------------------------------------------- #
# Run the fuction
# ---------------------------------------------------------------------------- #

hcrs_options <- c(1, 2,3,5,10)
sim_results <- list()

for(ssp in ssps){
  message("\nBuilding Scene for SSP: ", ssp)
  current_scene <- F_clim_sim_scene(
    scene=scene_bioen_best,
    ssp = ssp,
    cons = TRUE,
    resp = TRUE,
    buf = FALSE,
    pcod_rec = TRUE,
    pcod_rec_method = "cauchy",
    bioen_sp = bioen_sp_noceph,
    tdc_hind = tdc_hind,
    tdr_hind = tdr_hind,
    managed_sp = managed_sp_list,
    f_equil = F_equil,
    f_zero = F_zero,
    f_scenario = "mean",
    f_ref_yrs = 2016:2020,
    climate_dir = "data/climate/",
    hind_yrs = hind_years,
    proj_yrs = 2021:2099,
    hind_data_start_yr = 1991,
    climate_data_start_yr = 1980,
    verbose = FALSE
  )
  

  
  for(hcr_val in hcrs_options){
    run_name <- paste0("SSP", ssp, "_HCR", hcr_val)
    message(" Running sim: ", run_name)
    
    out <- a3_hcr_clim_sim(
      ssps = ssp,
      scene = current_scene,
      target_F = F_meanlast,
      target_B = target_bio,
      cap = FALSE,
      hcr = hcr_val
      )
    sim_results[[run_name]] <- out
  }
}

message("All done!!!")

# ---------------------------------------------------------------------------- #
# Plot ####
# ---------------------------------------------------------------------------- #
all_bio_data <- data.frame()
for (run_name in names(sim_results)) {
  # Extract SSP and HCR from the run name (e.g., "SSPpersist_HCR1")
  # This splits "SSPpersist_HCR1" into c("SSPpersist", "HCR1")
  run_parts <- strsplit(run_name, "_")[[1]]
  ssp_val <- run_parts[1]
  hcr_val <- run_parts[2]
  
  # Extract the annual biomass matrix
  rsim_obj <- sim_results[[run_name]]$sim_out
  bio_matrix <- rsim_obj$annual_Biomass
  
  # Convert to dataframe and add metadata columns
  bio_df <- as.data.frame(bio_matrix)
  bio_df$Year <- as.numeric(rownames(bio_matrix))
  bio_df$SSP  <- ssp_val
  bio_df$HCR  <- hcr_val
  bio_df$Metric <- "Total_Biomass"
  
  n_years <- length(all_years)
  annual_ssb_matrix <- matrix(NA, nrow = n_years, ncol = ncol(rsim_obj$out_SSB))
  colnames(annual_ssb_matrix) <- colnames(rsim_obj$out_SSB)
  rownames(annual_ssb_matrix) <- all_years
  
  for (y in 1:n_years) {
    m_start <- (y - 1) * 12 + 1
    m_end   <- y * 12
    # Average the 12 months for each year
    annual_ssb_matrix[y, ] <- colMeans(rsim_obj$out_SSB[m_start:m_end, , drop = FALSE])
  }
  
  ssb_df <- as.data.frame(annual_ssb_matrix)
  ssb_df$Year <- all_years
  ssb_df$SSP  <- ssp_val
  ssb_df$HCR  <- hcr_val
  ssb_df$Metric <- "SSB"
  
  # Combine Both Metrics
  all_bio_data <- bind_rows(all_bio_data, bio_df, ssb_df)
}

# 2. Pivot the data to "long" format for ggplot
bio_data_long <- all_bio_data %>%
  select(Year, SSP, HCR, Metric, all_of(managed_sp_list)) %>%
  filter(HCR %in% c("HCR1","HCR3", "HCR5")) |> 
  pivot_longer(
    cols = all_of(managed_sp_list), 
    names_to = "Species", 
    values_to = "Biomass"
  )

assessed_data <- bio_data_long %>%
  mutate(
    Is_SSB_Stock = Species %in% ssb_stocks,
    Keep = case_when(
      Is_SSB_Stock & Metric == "SSB" ~ TRUE,
      !Is_SSB_Stock & Metric == "Total_Biomass" ~ TRUE,
      TRUE ~ FALSE
    )
  ) %>%
  filter(Keep == TRUE) %>%
  mutate(Year = as.numeric(Year))

targets_plot <- data.frame(
  Species = managed_sp_list,
  B40_target = NA,
  B50_target = NA,
  Metric_Used = NA
)

for (sp in managed_sp_list) {
  if (sp %in% ssb_stocks) {
    targets_plot$B40_target[targets_plot$Species == sp] <- target_bio[sp, "B40_SSB"]
    targets_plot$B50_target[targets_plot$Species == sp] <- target_bio[sp, "B50_SSB"]
    targets_plot$Metric_Used[targets_plot$Species == sp] <- "SSB"
  } else {
    targets_plot$B40_target[targets_plot$Species == sp] <- target_bio[sp, "B40"]
    targets_plot$B50_target[targets_plot$Species == sp] <- target_bio[sp, "B50"]
    targets_plot$Metric_Used[targets_plot$Species == sp] <- "Total Biomass"
  }
}

# 3. Filter for specific species you want to compare
plot_species <- c("arrowtooth_flounder_adult", "atka_mackerel", "flathead_sole_adult", 
  "longnose_skate","pacific_cod_adult", "pacific_halibut_adult",
  "rex_sole_adult",  "sablefish_adult", "walleye_pollock_adult")

plot_data <- assessed_data %>% filter(Species %in% plot_species)
plot_targets <- targets_plot %>% filter(Species %in% plot_species)

# 4. Generate the Plot
hcr_plot <- ggplot(plot_data, aes(x = Year, y = Biomass, color = HCR, linetype = SSP, 
                                  linewidth = 2)) +
  geom_hline(data = plot_targets, aes(yintercept = B40_target), 
             color = "#009E73", linetype = "dashed", alpha = 0.7, linewidth = 1) +
  geom_hline(data = plot_targets, aes(yintercept = B50_target), 
             color = "#e1be6a", linetype = "dotted", alpha = 0.7, linewidth = 1) +
  geom_line(linewidth = 0.8) +
  facet_wrap(~Species, scales = "free_y", ncol = 3) +
  scale_color_viridis_d(option = "plasma", end = 0.8) + # Nice color palette
  theme_minimal() +
  labs(
    #title = "Projected Biomass across Climate Scenarios and HCRs",
    x = "Year",
    y = "Biomass (t*km^-2)",
    color = "",
    linetype = ""
  ) +
  theme(
    legend.position = "bottom",
    #strip.background = element_rect(fill = "grey90"),
    strip.text = element_text(face = "bold", size= 14),
    axis.text.x = element_text(hjust = 1, size=14),
    axis.text.y = element_text(size=14),
    axis.title = element_text(size=14),
    legend.text = element_text(size=14),
    legend.title = element_text(size=14),
    panel.background = element_rect(fill = "transparent", color = NA), # Transparent panel
    plot.background = element_rect(fill = "transparent", color = NA),  # Transparent background
    legend.background = element_rect(fill = "transparent", color = NA), # Transparent legend
    legend.box.background = element_rect(fill = "transparent", color = NA) # Transparent legend box
  )
#+
#  guides(linetype=guide_legend(nrow = 2, byrow = TRUE), color = guide_legend(nrow = 2, byrow = TRUE))

plot_path <- file.path(bftarget_dir, "HCRs.png")
ggsave(plot_path, plot = hcr_plot , width = 12, height = 10, bg = "transparent", dpi = 300)
message("Saved plot: ", plot_path)
