#' ---------------------------------------------------------------------------- #
#' AUTHORS: Bia Dias
#' ORIGINAL CODE: Kerim Aydin
#' AFFILIATIONS: CICOES University of Washington
#' E-MAIL OF CORRESPONDENCE AUTHOR: bia.dias@noaa.gov
#' DATE: 17 March 2026
#' @description
#' 
#' code/Function_diagnostics_TEST.R
#' Purpose: functions for the diagnostics of the test suite
#' ---------------------------------------------------------------------------- #
#' Extract Diet and Flow Matrices for a predator
#' This function runs a simulation and extracts the flow and diet proportion matrices 
#' for a specified predator over the period interval (years)
#' 
#' @param scene an rsim scenario object
#' @param years a numeric vector of years to run the simulation
#' @param predator a character string of the predator name to extract the matrices 
#' 
#' @return a list containing two matrices: "flow" (annual flow to the predator) and "diet" (normalized diet proportions)
#' 
#' @export
#' 
#' @examples 
#' \dontrun{get_predator_diet(scene, years = 1990:2020, predator = "arrowtooth_flounder_adult")}
#' 

get_predator_diet <- function(scene, years, predator) {
  drun <- rsim.run(scene, "AB", years)
  from_species <- scene$params$spname[scene$params$PreyFrom +1]
  to_species   <- scene$params$spname[scene$params$PreyTo   +1]
  
  flow_mat <-     drun$annual_Qlink[,which(to_species == predator)]
  colnames(flow_matrix) <- from_species[which(to_species == predator)]
  
  diet_mat <- flow_mat / rowSums(flow_mat)
  
  return(list(flow =flow_mat, diet= diet_mat))
}


#' Extract derivatives (derivT) for target species over time
#' 
#' Steps throught the simulation years to extract the derivative values for diagnostics
#' (gains, losses, fishing rates, etc.) for a specified target species.
#' 
#' @param scene an rsim scenario object
#' @param years a numeric vector of years to run the simulation
#' @param target_species a character string of the target species name to extract derivatives
#' 
#' @return a named list of data frames, each containing the derivatives for the target species over time
#' 
#' @export
#' 

get_species_derivatives <- function(scene, years, target_species) {
  output <- list()
  for(sp in target_species){
    output_list[[sp]] <- data.frame(matrix(NA, length(years), 13))
    row.names(output_list[[sp]]) <- years
  }
for(i in seq_along(years)){
  current_years <- years[1:i]
  step_run <- rsim(scene, method="AB", years= current_years)
  
  deriv.table <- data.frame(step_run$end_state["Biomass"],
                            step_run$dyt[c("TotGain","TotLoss","DerivT", "FoodLoss",
                                           "FoodGain", "UnAssimLoss","ActiveRespLoss",
                                           "DetritalGain","FishingGain", "MzeroLoss",
                                           "FishingLoss", "DetritalLoss")],
                            row.names = step_run$params$spname)
  for(sp in target_species){
    output_list[[sp]][as.character(years[i]), ] <- deriv.table[sp,]
    
  }
}
for(sp in target_species){
  colnames(output_list[[sp]]) <- colnames(deriv.table)
  output_list[[sp]][, 2:13] <- output_list[[sp]][,2:13]/output$Biomass
}
return(output_list)
}

#' species derivates plots 
#' 
#' Plots the derivatives (biomass, fishing loss, net feeding rate) for a list of target species over time.
#' 
#' @param output_list a list of data frames generated by `get_species_derivatives()`
#' @param target_species a character vector of species to plot
#' @param scenario_name optional character string to include in plot titles for context
#' 
#' @return NULL. plots will be rendered in the plot window
#' @importFrom graphics par plot
#' @export
#' 

plot_sp_derivates <- function(output_list, target_species, scenario_name = NULL) {
  oldpar <- graphics::par(mfrow = c(length(target_species),3), mar=c(4,4,3,1))
  on.exit(graphics::par(oldpar))
  
  for(sp in target_species){
    out <- output_list[[sp]]
    
    graphics::plot(rownames(out),log(out$Biomass),xlab="year", ylab="log Biomass", 
                   main=paste(sp, scenario_name, sep=" "))
    
    graphics::plot(rownames(out), out$FishingLoss, xlab="year", ylab="F rate", 
                   main=paste(sp, scenario_name, sep=" "))
    
    graphics::plot(rownames(out), out$FoodGain - out$UnAssimLoss - out$ActiveRespLoss, xlab="year", 
         ylab="Net feeding rate", main=paste(sp, scenario_name, sep=" "))
    
  }
}